bmw:
  name: "BMW"
  display_name: "BMW"
  api_name: "BMW"
  slug: "bmw-espana"
  logo: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711732366/devon-janse-van-rensburg-cQHx11ku1Dk-unsplash_awimek.jpg"
  models:
    serie3:
      display_name: "Serie 3"
      api_name: "3__BMW_ER_SERIES"
      type: "modelgroup"
      slug: "serie-3"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1709738717/P90382613-the-new-bmw-m340d-xdrive-touring-black-sapphire-metallic-02-2020-2250px_lbjugy.jpg"
    serie5:
      display_name: "Serie 5"
      api_name: "5__BMW_ER_SERIES"
      type: "modelgroup"
      slug: "serie-5"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1709742619/bmw-serie-5-6553620815c4c_whkhqa.jpg"
    serie7:
      display_name: "Serie 7"
      api_name: "7__BMW_ER_SERIES"
      type: "modelgroup"
      slug: "serie-7"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1760600529/BMW_7-Series__G70__750e_1X7A1895_a_flg3vr.jpg"
    x1:
      display_name: "X1"
      api_name: "X1"
      type: "model"
      slug: "x1"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1709742759/bmw-x1-m35i-xdrive_tglqls.webp"
    x5:
      display_name: "X5"
      api_name: "X5"
      type: "model"
      slug: "x5"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1709742806/bmw-x5-front-view_h8pmdk.jpg"
    x6:
      display_name: "X6"
      api_name: "X6"
      type: "model"
      slug: "x6"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1709742963/BMW_X6_0-1200x675_xi1ceu.jpg"
    i4:
      display_name: "i4"
      api_name: "i4"
      type: "model"
      slug: "i4"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1760600528/BMW_i4_IAA_2021_1X7A0307_on0v6a.jpg"
    i8:
      display_name: "i8"
      api_name: "i8"
      type: "model"
      slug: "i8"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1709743152/840_560_bvq526.jpg"

mercedes:
  name: "MERCEDES"
  display_name: "Mercedes-Benz"
  api_name: "mercedes-benz"
  slug: "mercedes-espana"
  logo: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711731177/liam-martens-uUi5RQCyUdM-unsplash_xdjxst.jpg"
  models:
    a:
      display_name: "Clase A"
      api_name: "A-Klasse"
      type: "modelgroup"
      slug: "a"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711741512/MERCEDES_CLASE_A_2018-e1621413018502-1_asdi3s.jpg"
    cla:
      display_name: "CLA"
      api_name: "CLA-Klasse"
      type: "modelgroup"
      slug: "cla"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711741513/mercedes-benz-2019-15g-1-1024x683_e87ylz.jpg"
    gla:
      display_name: "GLA"
      api_name: "GLA-Klasse"
      type: "modelgroup"
      slug: "gla"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711741516/primera-prueba-mercedes-1_g_xdwolt.jpg"
    glc:
      display_name: "GLC"
      api_name: "GLC-Klasse"
      type: "modelgroup"
      slug: "glc"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711741513/mercedes-benz-2019-1_g_v4nv6d.jpg"
    gle:
      display_name: "GLE"
      api_name: "GLE-Klasse"
      type: "modelgroup"
      slug: "gle"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1760600525/Mercedes-Benz_W167_350de_at_IAA_2019_IMG_0565_ojelyl.jpg"
    s:
      display_name: "Clase S"
      api_name: "S-Klasse"
      type: "modelgroup"
      slug: "s"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711741513/Mercedes-S-580e-2021-15_w44xzq.jpg"
    eqv:
      display_name: "EQV"
      api_name: "EQV"
      type: "model"
      slug: "eqv"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1760600525/Mercedes-Benz_EQV_300_Design-Paket_Lang__V_447__2._Facelift____f_15062025_yewels.jpg"

audi:
  name: "AUDI"
  display_name: "Audi"
  api_name: "AUDI"
  slug: "audi-espana"
  logo: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711812955/302afc26-f0cf-4da0-a023-b060706af3ee_fmclsg.jpg"
  models:
    a3:
      display_name: "A3"
      api_name: "A3"
      type: "model"
      slug: "a3"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711798497/remy-lovesy-19M7TbSch2U-unsplash_v7qkfc.jpg"
    a4:
      display_name: "A4"
      api_name: "A4"
      type: "model"
      slug: "a4"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711798509/remy-lovesy-LO8rqX93FgQ-unsplash_erca3u.jpg"
    q3:
      display_name: "Q3"
      api_name: "Q3"
      type: "model"
      slug: "q3"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711798502/remy-lovesy-L69quRDsm8A-unsplash_rb0mfn.jpg"
    q4:
      display_name: "Q4"
      api_name: "Q4"
      type: "model"
      slug: "q4"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1760600526/original_rqweer.jpg"
    q5:
      display_name: "Q5"
      api_name: "Q5"
      type: "model"
      slug: "q5"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711798485/eduardo-flores-FxjjnBvXq-Y-unsplash_lkbfqe.jpg"
    q6:
      display_name: "Q6"
      api_name: "Q6"
      type: "model"
      slug: "q6"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1760600522/Audi_Q4_e-tron_40_1X7A7053_p4db2g.jpg"
    q8:
      display_name: "Q8"
      api_name: "Q8"
      type: "model"
      slug: "q8"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711798494/maksym-tymchyk-bb6NaemzpGY-unsplash_og4wlz.jpg"

porsche:
  name: "PORSCHE"
  display_name: "Porsche"
  api_name: "PORSCHE"
  slug: "porsche-espana"
  logo: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711812954/porsche_992_head_on_hpudjw.jpg"
  models:
    macan:
      display_name: "Macan"
      api_name: "MACAN"
      type: "model"
      slug: "macan"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711801748/michail-dementiev-EC7juxmFUa4-unsplash_epyi44.jpg"
    cayenne:
      display_name: "Cayenne"
      api_name: "CAYENNE"
      type: "model"
      slug: "cayenne"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711801746/jaime-castrillon-G9C5t5z6h0k-unsplash_cvyl3k.jpg"
    panamera:
      display_name: "Panamera"
      api_name: "PANAMERA"
      type: "model"
      slug: "panamera"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711801746/ayman-hallak-kjozrvqXnuY-unsplash_e7vbsl.jpg"
    taycan:
      display_name: "Taycan"
      api_name: "TAYCAN"
      type: "model"
      slug: "taycan"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711801745/or-hakim-0qcexMtNjR4-unsplash_ni6rb7.jpg"

volkswagen:
  name: "VW"
  display_name: "Volkswagen"
  api_name: "VW"
  slug: "volkswagen-espana"
  logo: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711731576/chris-osmond-54tC25jNoWA-unsplash_axwylx.jpg"
  models:
    polo:
      display_name: "Polo"
      api_name: "POLO"
      type: "model"
      slug: "polo"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711806582/3dvisu-XnwC7-9SZf4-unsplash_xuu0oy.jpg"
    golf:
      display_name: "Golf"
      api_name: "GOLF"
      type: "model"
      slug: "golf"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711806580/martin-katler-SuD4h8Gpgok-unsplash_ggebds.jpg"
    tiguan:
      display_name: "Tiguan"
      api_name: "TIGUAN"
      type: "model"
      slug: "tiguan"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711806584/unnamed_tihgpj.jpg"
    t7california:
      display_name: "T7 California"
      api_name: "T7 CALIFORNIA"
      type: "model"
      slug: "t7-california"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1760600529/VW_California_Beach_Tour__T7____h_01012025_aiaywu.jpg"
    id3:
      display_name: "ID.3"
      api_name: "ID.3"
      type: "model"
      slug: "id3"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1760600529/Volkswagen_ID.3_at_IAA_2019_IMG_0212_bxjila.jpg"
    touareg:
      display_name: "Touareg"
      api_name: "TOUAREG"
      type: "model"
      slug: "touareg"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711806582/captivating-ride-with-a-volkswagen-touareg-8dy2ctaugaekcvhd_rse1ni.jpg"

mini:
  name: "MINI"
  display_name: "Mini"
  api_name: "MINI"
  slug: "mini-espana"
  logo: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711731719/devon-janse-van-rensburg-q039kSjYlD4-unsplash_f5kzny.jpg"
  models:
    cooper:
      display_name: "Cooper"
      api_name: "COOPER"
      type: "model"
      slug: "cooper"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711807975/devon-janse-van-rensburg-i7ipLokGGGo-unsplash_egkonb.jpg"
    aceman:
      display_name: "Aceman"
      api_name: "ACEMAN"
      type: "model"
      slug: "aceman"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1760600525/Mini_Aceman_John_Cooper_Works_DSC_2680_kj2xmp.jpg"
    countryman:
      display_name: "Countryman"
      api_name: "COOPER_COUNTRYMAN"
      type: "model"
      slug: "countryman"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711807975/burak-sahin-cyLZiU5r4OQ-unsplash_qhhtpg.jpg"

cupra:
  name: "CUPRA"
  display_name: "Cupra"
  api_name: "CUPRA"
  slug: "cupra-espana"
  logo: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711732019/pierre-saigot-SqPs9Jg-8xk-unsplash_scflhl.jpg"
  models:
    tavascan:
      display_name: "Tavascan"
      api_name: "TAVASCAN"
      type: "model"
      slug: "tavascan"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1760600522/Cupra_Tavascan__IAA_Summit_2023__Munich__P1110846_ifak81.jpg"
    formentor:
      display_name: "Formentor"
      api_name: "FORMENTOR"
      type: "model"
      slug: "formentor"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711809221/marcel-hoberg-PGmkdB6YWbY-unsplash_a3vvyg.jpg"
    leon:
      display_name: "León"
      api_name: "LEON"
      type: "model"
      slug: "leon"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711809221/nils-arfert-pZ-iur48Z3Y-unsplash_fnjpli.jpg"
    born:
      display_name: "Born"
      api_name: "BORN"
      type: "model"
      slug: "born"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711809220/swansway-motor-group-eupfOjJDkqQ-unsplash_nlhw7i.jpg"
    terramar:
      display_name: "Terramar"
      api_name: "TERRAMAR"
      type: "model"
      slug: "terramar"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1760600526/Cupra_Terramar_VZ_IMG_2330_yfhbvi.jpg"

tesla:
  name: "TESLA"
  display_name: "Tesla"
  api_name: "TESLA"
  slug: "tesla-espana"
  logo: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711732123/dmitry-novikov-49gi04Retc4-unsplash_tsjq0k.jpg"
  models:
    models:
      display_name: "Model S"
      api_name: "Model S"
      type: "model"
      slug: "model-s"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711809972/caras-creative-studio-Wl3tBOG96Jk-unsplash_pecbmh.jpg"
    model3:
      display_name: "Model 3"
      api_name: "Model 3"
      type: "model"
      slug: "model-3"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711809973/martin-katler-DiJR_M1Mv_A-unsplash_bmutcm.jpg"
    modely:
      display_name: "Model Y"
      api_name: "Model Y"
      type: "model"
      slug: "model-y"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711809973/craventure-media-f9cTLsjnEi0-unsplash_os1gyh.jpg"
    modelx:
      display_name: "Model X"
      api_name: "Model X"
      type: "model"
      slug: "model-x"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1711809972/jorgen-hendriksen-dLn6nUY-5zg-unsplash_avsclq.jpg"

byd:
  name: "BYD"
  display_name: "BYD"
  api_name: "BYD"
  slug: "byd-espana"
  logo: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1760600522/BYD_Seal_IAA_2023_1X7A0371_aqmib6.jpg"
  models:
    seal:
      display_name: "Seal"
      api_name: "SEAL"
      type: "model"
      slug: "seal"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1760600522/BYD_Seal_IAA_2023_1X7A0371_aqmib6.jpg"
    atto3:
      display_name: "Atto 3"
      api_name: "ATTO 3"
      type: "model"
      slug: "atto-3"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1760600520/BYD_Atto_3_1X7A6495_i0lz8u.jpg"
    dolphin:
      display_name: "Dolphin"
      api_name: "DOLPHIN"
      type: "model"
      slug: "dolphin"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1760600518/2023_BYD_Dolphin_Standard_Range_k3bmdh.jpg"
    sealu:
      display_name: "Seal U"
      api_name: "SEAL U"
      type: "model"
      slug: "seal-u"
      image: "https://res.cloudinary.com/dd7x7bqya/image/upload/v1760600521/BYD_Seal_U_DM-i_GIMS_2024_1X7A2192_kq1njh.jpg"
